mental_health_activities = {
    "meditation": "🧘 Try a 5-minute guided meditation to boost your mental well-being.",
    "breathing": "🌬️ Take 10 deep breaths to calm your mind and body.",
    "stretching": "🧎 Stand up and stretch to help your muscles relax.",
    "yoga": "🧘‍♂️ Engage in a 15-minute yoga session to relax your body and mind.",
    "walking": "🚶 A 20-minute walk in the fresh air can work wonders for your well-being.",
    "workout": "🏋️‍♂️ A quick 10-minute workout can boost your mood!",
    "journaling": "📖 Spend 10 minutes writing down your thoughts and feelings in a journal.",
    "listening_to_music": "🎵 Listen to your favorite music for a mood boost.",
    "drawing": "🎨 Spend some time drawing or coloring to express yourself creatively.",
    "reading": "📚 Read a chapter of a book you enjoy to escape and relax.",
    "gardening": "🌱 Spend time tending to your plants and enjoy the therapeutic benefits of gardening.",
    "breathing_exercises": "💨 Practice deep breathing exercises to reduce stress.",
    "gratitude_list": "🙏 Write down three things you're grateful for today.",
    "progressive_muscle_relaxation": "💪 Try progressive muscle relaxation to ease tension.",
    "nature_watching": "🌳 Spend some time observing nature or taking in the outdoors.",
    "mindfulness": "🧠 Practice mindfulness by focusing on the present moment.",
    "aromatherapy": "🕯️ Use essential oils or scented candles to create a calming atmosphere.",
    "bubble_bath": "🛁 Take a relaxing bubble bath to unwind.",
    "digital_detox": "📵 Take a break from screens for an hour to rest your eyes and mind.",
    "positive_affirmations": "🌟 Repeat positive affirmations to boost your confidence and mood.",
    "puzzle_solving": "🧩 Solve a puzzle or play a brain game to engage your mind.",
    "guided_visualization": "🌈 Listen to a guided visualization to relax and imagine a peaceful place.",
    "cooking": "🍳 Try cooking a new recipe as a way to engage your senses and creativity.",
    "crafting": "🛠️ Work on a craft project to keep your hands and mind busy.",
    "dance": "💃 Dance to your favorite music to lift your spirits and get some exercise.",
    "comedy": "😂 Watch a comedy show or read jokes to make yourself laugh.",
    "spending_time_with_pet": "🐕 Spend time with a pet for companionship and stress relief.",
    "sleep_routine": "😴 Establish a calming bedtime routine to improve your sleep quality.",
    "personal_project": "🖼️ Work on a personal project or hobby that you enjoy.",
    "mindful_eating": "🍽️ Practice mindful eating by savoring each bite and eating slowly.",
    "self_massage": "💆 Give yourself a hand or neck massage to release tension.",
    "volunteering": "🤝 Spend time helping others through volunteering to feel a sense of purpose.",
    "goal_setting": "🎯 Set small, achievable goals for yourself and track your progress.",
    "creative_writing": "✍️ Try creative writing or poetry to express your feelings.",
    "breathing_meditation": "🧘‍♀️ Combine breathing exercises with meditation for relaxation.",
    "affirmation_jars": "🌟 Create an affirmation jar with positive notes to read when needed.",
    "painting": "🖌️ Express yourself through painting or other visual arts.",
    "mindful_walking": "🚶‍♂️ Practice mindful walking by paying attention to each step and your surroundings.",
    "sensory_exploration": "👃 Engage your senses by exploring different textures, smells, and tastes.",
    "hot_beverage": "☕ Enjoy a hot beverage like tea or hot chocolate for comfort and relaxation.",
    "yoga_stretching": "🧘‍♀️ Combine yoga with stretching exercises for a full-body relaxation session.",
    "creative_problem_solving": "🧠 Engage in creative problem-solving activities to stimulate your mind.",
    "gratitude_journal": "📓 Start a gratitude journal and write daily entries of what you're thankful for.",
    "mindful_breathing": "🌬️ Practice mindful breathing to center yourself and reduce stress.",
    "body_scan": "🛌 Do a body scan meditation to become aware of physical sensations and relax.",
    "simple_exercises": "🏃 Try simple exercises like squats or jumping jacks to get your blood flowing.",
    "self_care_routine": "🛀 Create a self-care routine that includes activities that make you feel good.",
    "reminiscing": "📷 Spend time reminiscing about happy memories or looking at old photos.",
    "visualization": "🌟 Use visualization techniques to imagine achieving your goals.",
    "calm_down_activity": "🧘 Engage in an activity that helps you calm down, such as reading or listening to soothing music.",
    "positive_self_talk": "🗣️ Practice positive self-talk to build self-confidence and reduce negative thoughts.",
    "yoga_nidra": "🛌 Try Yoga Nidra, a guided meditation practice that promotes deep relaxation.",
    "tai_chi": "🥋 Engage in Tai Chi for gentle exercise and relaxation.",
    "relaxation_audio": "🎧 Listen to relaxation audio or guided meditations to de-stress.",
    "social_interaction": "👫 Connect with friends or family for support and companionship.",
    "creative_expressions": "🎨 Try other forms of creative expression such as sculpture or digital art.",
    "appreciation_list": "💖 Make a list of things you appreciate about yourself and your life.",
    "motivational_quotes": "🗯️ Read or listen to motivational quotes to inspire and uplift yourself.",
    "relaxing_hobbies": "🎲 Engage in hobbies that help you relax, like knitting or model building.",
    "warm_up_exercises": "🧗 Perform warm-up exercises to prepare your body for activity and reduce tension.",
    "mental_break": "🧘‍♂️ Take a short mental break to step away from stressors and recharge.",
    "self_reflection": "🪞 Spend time in self-reflection to understand your feelings and thoughts.",
    "breathwork": "🌬️ Practice breathwork techniques to manage anxiety and stress.",
    "engaging_in_play": "🎲 Allow yourself to play and have fun, whether through games or creative activities.",
    "learning_new_skill": "📚 Take up a new skill or hobby to engage your mind and boost your confidence.",
    "connecting_with_nature": "🌲 Spend time connecting with nature, like hiking or sitting in a park.",
    "mindful_eating_experience": "🍇 Have a mindful eating experience where you focus on the taste and texture of your food.",
    "visual_art": "🖼️ Explore visual arts such as drawing, painting, or photography to express yourself.",
    "relaxation_techniques": "💤 Try various relaxation techniques to see which works best for you."
}
